validate:
  name:
    maximum: 50
  email:
    maximum: 255
  password:
    minimum: 6
gravatar:
  size: 80
session_controller:
  session: 1
views:
  users:
    gravatar: 50
user_controller:
  per_paginate: 20
model:
  user:
    password_reset_expired: 2
